### ISSUE TITLE
Incorrect Error Message Can Be Confusing

### ISSUE THREAD

**Issue by mrgrim** [d4rkc0d3r/FactorioPumpjackBlueprint#12]
The error is thrown on line 81 in Program.cs:
```
default: throw new Exception($"Invalid pumpjack direction {entity.Direction}, possible values are [0, 2, 6, 8]");
```
Shouldn't happen, but can due to bug #11. The possible values list should read "0, 4, 8, 12". It would probably be better to use use the constants in composing the string, e.g.:
```
default: throw new Exception($"Invalid pumpjack direction {entity.Direction}, possible values are [{Direction.North}, {Direction.East}, {Direction.South}, {Direction.West}]");
```
Please consider I am unfamiliar with C# so I don't know if those expressions need explicit casting or conversion to a string.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Update the exception message for invalid pumpjack direction to use Direction constants and correct values.

You can review changes in this commit: https://github.com/lattaai13/d4rkc0d3r-FactorioPumpjackBlueprint-12/commit/8bb341c50926944cb3015aa857a4b8ac69d9d432.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
